In [ ]:
#variable
a=10
print(a)

10


In [ ]:
#variable
x=10
print("Iam",a,"year old")

Iam 10 year old


In [ ]:
#sum of two numbers
x=int(input("enter first number: "))
y=int(input("enter secound number: "))
print("sum is",x+y)
print("difference is",x-y)
print("product is",x*y)
print("quotient is",x/y)
print("Reminder is",x%y)
print("power to a be  is",x**y)
print("float div is",x//76y)




enter first number: 98
enter secound number: 76
sum is 174
difference is 22
product is 7448
quotient is 1.2894736842105263
Reminder is 22
power to a be  is 21536828643569064545821523989766916375901656156422969714379660229474586173004618340975140948605460874876371905141687563952783341456558505439549074702336
float div is 1


In [ ]:
#takig salary from the user if the salary is mor than 50K their is 10% tax print his final salary
#Syntx:
#if condition:
  #statement
#else:
  #statement
sal=int(input("enter your salary: "))
if sal>50000:
  print(sal-sal*0.1)
else:
  print("your salary is that 50k so,no tax")

enter your salary: 16000
your salary is that 50k so,no tax


In [ ]:
#get a salary from the user if the salary is more than or equal 50K apply 10% tax dection if the salary is greater than 50K apply 5% tax if the salary is more than 70K apply 12% tax if the salary is exits 1lakh print your promotion to next level
#LOGIC:
#0 TO 50K->5%
#51 TO 70K-->10%
#71K TO 1L-->12%
#MORE THAN IL -->PROMOTION...!
a=int(input("enter the salary: "))
if(a>=0 and 0<50000):
  print("tax is apply 5%",a-(a*5/100))
elif(a>=50000 and a<70000):
  print("tax is apply 10%",a-(a*10/100))
elif(a>=70000 and a<1000000):
  print("tax is apply 12%",a-(a*12/100))
else:
  print("your are promited......")


enter the salary: 500000
tax is apply 5% 475000.0


In [ ]:
#Range using loop
n=int(input("enter number: "))
for i in range(1,11):
  print(n,'X',i,'=',n*i)

enter number: 5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


In [ ]:
#while loop
n=int(input("enter number: "))
i=1
while(i<=10):
  print(n,"*",i,"=",n*i)
  i=i+1

enter number: 12
12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120


In [ ]:
#creating a list ***hetergenous***
p1=[98,"priya",76,"siri",7.5,True]
for i in p1:
  print(i)

98
priya
76
siri
7.5
True


In [ ]:
#mutable
p1.append("append")#adds element at back of the list
print(p1)

[98, 'priya', 76, 'siri', 7.5, True, 'append']


In [ ]:
#insert
p1.insert(5,"ujwala")#list name.insert(index,element)
print(p1)

[98, 'priya', 76, 'siri', 7.5, 'ujwala', True, 'append']


In [ ]:
#extend
p2=["joe","suji"]#list1.extend(list2)
p1.extend(p2)#p1+p2
print(p1)

[98, 'priya', 76, 'siri', 7.5, 'ujwala', True, 'append', 'joe', 'suji']


In [ ]:
#pop
p1.pop(7)
print(p1)

[98, 'priya', 76, 'siri', 7.5, 'ujwala', True, 'joe', 'suji']


In [ ]:
#remove
p1.remove(True)#listname.remove(element)
print(p1)

[98, 'priya', 76, 'siri', 'ujwala', 'joe', 'suji']


In [ ]:
#clear
p1.clear()
print(p1)

[]


In [ ]:
#create a list of random 10 integer elements print there squres in a new list
x=[78,32,37,64,14]
res=[]
for i in x:
  res.append(i*i)
  print(res)

[6084]
[6084, 1024]
[6084, 1024, 1369]
[6084, 1024, 1369, 4096]
[6084, 1024, 1369, 4096, 196]


In [ ]:
#list count
#new list=[output for]
x=[78,32,37,64,14]
res=[i*i for i in x]
print(res)

[6084, 1024, 1369, 4096, 196]


In [ ]:
#list count
#newlist=[output for if]
x=[78,32,37,64,14]
res=[i*i for i in x if i>50]
print(res)

[6084, 4096]


In [ ]:
#newlist=[(statement of if)if(condition)else(statement of else)for]
x=[78,32,37,64,14]
res=[i*i if i>50 else 'X' for i in x]
print(res)

[6084, 'X', 'X', 4096, 'X']


In [ ]:
#take the salary from the user if the salary less than 50k 10% tax otherwise 15% tax
sallist=[78000,50400,34000,23000,14000]
res=[i-i*0.1 if i<50000 else i-i*0.15 for i in sallist]
print(res)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#dictionary
#Syntax dictname={key:val,key:val....}
dict1={'mentor':'Jwalitha',98:'priya',76:'siri',68:'varshitha',22:'vyshu'}
print(dict1)

{'mentor': 'Jwalitha', 98: 'priya', 76: 'siri', 68: 'varshitha', 22: 'vyshu'}


In [ ]:
dict1={'mentor':'Jwalitha',98:'priya',76:'siri',68:'varshitha',22:'vyshu'}
print(dict1.values())

dict_values(['Jwalitha', 'priya', 'siri', 'varshitha', 'vyshu'])


In [ ]:
dict1={'mentor':'Jwalitha',98:'priya',76:'siri',68:'varshitha',22:'vyshu'}
print(dict1.keys())

dict_keys(['mentor', 98, 76, 68, 22])


In [ ]:
dict1=(['Jwalitha', 'priya', 'siri', 'varshitha', 'vyshu'])
print(dict1[1])

priya


In [ ]:
dict3={"dept":"cse","details":{"year":"||","sec":"d","count":71}}
print("year is",dict3["details"]["year"])
print("sec is",dict3["details"]["sec"])
print("strength is",dict3["details"]["count"])

year is ||
sec is d
strength is 71


In [ ]:
id=[98,76,68,94,85]
names=["priya","ujwala","siri","joe","suji"]
new_zip=(zip(id,names))
for i in new_zip:
  print(i)

(98, 'priya')
(76, 'ujwala')
(68, 'siri')
(94, 'joe')
(85, 'suji')


In [ ]:
id=[98,76,68,94,85]
names=["priya","ujwala","siri","joe","suji"]
new_dict=dict(zip(id,names))
print(new_dict)

{98: 'priya', 76: 'ujwala', 68: 'siri', 94: 'joe', 85: 'suji'}


In [ ]:
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.ndim)

1


In [ ]:
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.shape)

(4,)


In [ ]:
#create 2D array
import numpy as np
A=np.array([[1,2,3,4][6,7,8,9]])
print(A.ndim)
print(A.shape)
print(A)


In [ ]:
#3D array
import numpy as np
b=np.array([[[1,2],["a","b"],["ab","bc"]],[[4,5],["m","g"],["cd","ec"]]])
print(b.ndim)
print(b.shape)
print(b)


3
(2, 3, 2)
[[['1' '2']
  ['a' 'b']
  ['ab' 'bc']]

 [['4' '5']
  ['m' 'g']
  ['cd' 'ec']]]


In [ ]:
A=np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.linspace(2,3,20)
print(a)

[2.         2.05263158 2.10526316 2.15789474 2.21052632 2.26315789
 2.31578947 2.36842105 2.42105263 2.47368421 2.52631579 2.57894737
 2.63157895 2.68421053 2.73684211 2.78947368 2.84210526 2.89473684
 2.94736842 3.        ]


In [ ]:
#creating tuple
num=(1,2,-98)
print(num)

(1, 2, -98)


In [ ]:
#length of tuple
a=('priya','ujwala','darshini',98,-45,0.45)
print(len(a))

6


In [ ]:
#loop
a=('priya','ujwala','darshini',98,-45,0.45)
for i in a:
  print(i)



priya
ujwala
darshini
98
-45
0.45


In [ ]:
#update tuple
x=('priya','ujwala','darshini',98,-45,0.45)
y = list(x)
y[2] = "siri"
x = tuple(y)
print(x)


('priya', 'ujwala', 'siri', 98, -45, 0.45)


In [ ]:
a=[8,6,7,98,23]
a.sort
print(a)

[8, 6, 7, 98, 23]


In [ ]:
#loop
thistuple=("priya","ujwala","darshini")
for x in thistuple:
  print(x)

priya
ujwala
darshini


In [ ]:
#creating a set
a={'priya','ujwala','darshini',98,-45,0.45}
print(a)

{0.45, 98, -45, 'priya', 'darshini', 'ujwala'}


In [ ]:
#add in set
a={'priya','ujwala','darshini',98,-45,0.45}
a.add('siri')
print(a)

{0.45, 98, -45, 'priya', 'darshini', 'ujwala', 'siri'}


In [ ]:
#loop in set
a={'priya','ujwala','darshini',98,-45,0.45}
for i in a:
  print(i)

0.45
98
-45
priya
darshini
ujwala


Sorting


In [ ]:
a=[8,6,7,98,23]
b=sorted(a)
print(b)

[6, 7, 8, 23, 98]


In [ ]:
a=(77,34,35,88,29,87)
b=sorted(a)
print(a)
print(b)

(77, 34, 35, 88, 29, 87)
[29, 34, 35, 77, 87, 88]


In [ ]:
#colmu