In [ ]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(3,4)
print(A)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.linspace(2,3,12).reshape(2,6)
print(a)

[[2.         2.09090909 2.18181818 2.27272727 2.36363636 2.45454545]
 [2.54545455 2.63636364 2.72727273 2.81818182 2.90909091 3.        ]]


In [ ]:
b=np.array([63,37,99,46,47,38,22,98]).reshape(2,2,2)
print(b)

[[[63 37]
  [99 46]]

 [[47 38]
  [22 98]]]


In [ ]:
b=np.array([63,37,99,46,47,38,22,98])
b.resize(2,2,2)#changes the space of orginal array
#reshape--changes need saving in another variable
print(b)


[[[63 37]
  [99 46]]

 [[47 38]
  [22 98]]]


In [ ]:
a=np.array([63,37,99,46,])
b=np.array([8,3,6,2])#list will throw while arrays iterate themselves
c=a-b
print(c)

[55 34 93 44]


In [ ]:
a=np.array([89,98,73,77])
b=np.array([84,58,39,28])
c=a+b
print(c)



[173 156 112 105]


In [ ]:
a=np.array([89,98,73,77]).reshape(2,2)
b=np.array([84,58,39,28]).reshape(2,2)
print(a)
print(b)
print("---------******--------------")
print(b)
c=a*b#matrix multiplication
print("--------****----------")
print(c)




[[89 98]
 [73 77]]
[[84 58]
 [39 28]]
---------******--------------
[[84 58]
 [39 28]]
--------****----------
[[7476 5684]
 [2847 2156]]


In [ ]:
a=np.array([89,98,73,77]).reshape(2,2)
b=np.array([84,58,39,28]).reshape(2,2)
print(a)
print(b)
print("---------******--------------")
print(b)
c=a@b#one on one multiplication
print("--------****----------")
print(c)




[[89 98]
 [73 77]]
[[84 58]
 [39 28]]
---------******--------------
[[84 58]
 [39 28]]
--------****----------
[[11298  7906]
 [ 9135  6390]]


In [ ]:
a=np.array([89,98,73,77]).reshape(2,2)
b=np.array([84,58,39,28]).reshape(2,2)
print(a)
print(b)
print("---------******--------------")
print(b)
c=a.dot(b)#matrix multiplication
print("--------****----------")
print(c)




[[89 98]
 [73 77]]
[[84 58]
 [39 28]]
---------******--------------
[[84 58]
 [39 28]]
--------****----------
[[11298  7906]
 [ 9135  6390]]


In [ ]:
a=np.array([7,4,66,37])
print(a.min())#max and min only accepts int &float
print(a.max())

4
66


In [ ]:
a=np.array({7.7,5.7,9.9})
print(a.min())
print(a.max())

{9.9, 5.7, 7.7}
{9.9, 5.7, 7.7}


In [ ]:
a=np.array([74,47,87,78]).reshape(2,2)
print(a)
print("-------*****--------")
print(a.max(axis=0))#axis 0-colum
print("------****-----")
print(a.max(axis=1))#axiz 1-row

[[74 47]
 [87 78]]
-------*****--------
[87 78]
------****-----
[74 87]


In [ ]:
#joing arrays


In [ ]:
a=np.array([89,98,73,77]).reshape(2,2)
b=np.array([84,58,39,28]).reshape(2,2)
print(a)
print("---------******--------------")
print(b)
print("after vertically stacking the arrays!")
print(np.vstack((a,b)))



[[89 98]
 [73 77]]
---------******--------------
[[84 58]
 [39 28]]
after vertically stacking the arrays!
[[89 98]
 [73 77]
 [84 58]
 [39 28]]


In [ ]:
a=np.array([89,98,73,77]).reshape(2,2)
b=np.array([84,58,39,28]).reshape(2,2)
print(a)
print("---------******--------------")
print(b)
print("after vertically stacking the arrays!")
print(np.vstack((a,b)))



In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("after dstack")
print(np.dstack(a))#no.of rows-->no.of groups
#no.of col in every group-->no.of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(2,5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit (a,2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(21,39).reshape(3,6)
print(a)
print(a.argmax())

[[21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]]
17


In [ ]:
a=np.linspace(17,12,18).reshape(3,6)
print(a)
print(a.argmax())

[[17.         16.70588235 16.41176471 16.11764706 15.82352941 15.52941176]
 [15.23529412 14.94117647 14.64705882 14.35294118 14.05882353 13.76470588]
 [13.47058824 13.17647059 12.88235294 12.58823529 12.29411765 12.        ]]
0


In [ ]:
a=np.array([89,98,76,67]).reshape(2,2)
print(a)
print(a.argmax(axis=0))#p0stion[0 0 0 0
                               # 1 1 1 1]

[[89 98]
 [76 67]]
[0 0]


In [ ]:
a=np.array([89,98,76,67]).reshape(2,2)
print(a)
print(a.argmax(axis=1))

[[89 98]
 [76 67]]
[1 0]


In [ ]:
a=np.array([89,98,76,67]).reshape(2,2)
print(a)
print(a.argmin(axis=0))

[[89 98]
 [76 67]]
[1 1]


In [ ]:
a=np.array([89,98,76,67]).reshape(2,2)
print(a)
print(a.argmin(axis=1))

[[89 98]
 [76 67]]
[0 1]


In [ ]:
a=np.array([89,98,76,67]).reshape(2,2)
print(a)
print(a.argmin())

[[89 98]
 [76 67]]
3


In [ ]:
#mean,median,mode,var
a=np.array([12,34,25,66,71,88])
print("mean: ",np.mean(a))
print("median: ",np.median(a))
print("variance: ",np.var(a))
print("standard dev: ",np.std(a))

mean:  49.333333333333336
median:  50.0
variance:  743.888888888889
standard dev:  27.274326552435515


In [ ]:
a=np.pi
print(a)#radians

3.141592653589793


In [ ]:
np.rad2deg(a)

180.0

In [ ]:
a=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(a)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(a)

array([ 45.,  60.,  90., 180.])

In [ ]:
c=np.array([0,30,45,60,90,120,180])
print(np.deg2rad(c))


[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
c=np.array([30,45,60,90,120,180])
d=np.deg2rad(c)
print(d)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
np.sin(c)

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666,  0.58061118,
       -0.80115264])

In [ ]:
np.cos(c)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362,  0.81418097,
       -0.59846007])

In [ ]:
np.tan(c)

array([-6.4053312 ,  1.61977519,  0.32004039, -1.99520041,  0.71312301,
        1.33869021])

In [ ]:
np.arcsin(1)#sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)#cos^-1

0.0

In [ ]:
np.arctan(1)#tan^-1

0.7853981633974483

In [ ]:
a=6
b=4
print(np.hypot(a,b))#hypotheuse

7.211102550927978


In [ ]:
a=8
b=6
print(np.hypot(a,b))#hypotheuse

10.0


In [ ]:
#Searching
a=np.array([90,3,45,21,34,90,21])
print(np.where(a==21))

(array([3, 6]),)


In [ ]:
#Searching
a=np.array([90,3,45,21,34,90,21])
print(np.where(a%2==0))#even

(array([0, 4, 5]),)


In [ ]:
#Searching
a=np.array([90,3,45,21,34,90,21])
print(np.where(a>25))#greaterthan 25

(array([0, 2, 4, 5]),)


In [ ]:
#search sorted
import numpy as np
a=np.array([90,3,45,21,34,90,21])
print(np.searchsorted(a,90))#outputs the index of a sorted element


5


In [ ]:
#liner algebra and ufunc
a=np.array([6,24,60,12,18])
b=np.array([6,4,10,5,4])
print("addition: ",np.add(a,b))
print("subtraction:",np.subtract(a,b))
print("mod:",np.mod(a,b))
print("divmod:",np.divmod(a,b))
print("div:",np.divide(a,b))



addition:  [12 28 70 17 22]
subtraction: [ 0 20 50  7 14]
mod: [0 0 0 2 2]
divmod: (array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))
div: [1.  6.  6.  2.4 4.5]


In [ ]:
a=np.array([6,24,60,12,18])
print(np.diff(a))

[ 18  36 -48   6]


In [ ]:
a=np.array([6,24,60,12,18])
print(np.sort(a))

[ 6 12 18 24 60]


In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([6,4,10,5,4])
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[ 4  5  6 10 12 18 24 60]
[6]
[12 18 24 60]


In [ ]:
#rounding
a1=np.around([-3.16636,4])
print(a1)

[-3.  4.]


In [ ]:
#rounding
a1=np.floor([-3.1666,3.6667])
print(a1)

[-4.  3.]


In [ ]:
#rounding
a1=np.ceil([-3.1666,3.1])
print(a1)

[-3.  4.]


In [ ]:
#rounding
a1=np.fix([-3.1666,3.6667])
print(a1)

[-3.  3.]


In [ ]:
a1=np.trunc([-4.6787,9.599])
print(a1)

[-4.  9.]


In [ ]:
#more function
a=np.array([3,4,16,19,10])
print(np.cumsum(a))

[ 3  7 23 42 52]


In [ ]:
#more function
a=np.array([3,4,16,19,10])
print(np.cumprod(a))

[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [ ]:
ar=np.array([45,65,30])
print(np.lcm.reduce(ar))

1170


In [ ]:
ar=np.array([45,65,30])
print(np.gcd.reduce(ar))

5


In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#random
from numpy import random as rd
a=rd.rand()#default limit 0to 0.99
print(a)

0.2300128562111704


In [ ]:
#random
from numpy import random as rd
a=rd.rand(10)#default limit 0to 0.99
print(a)

[0.86023557 0.15920895 0.64506324 0.01865785 0.53721139 0.17006412
 0.08064388 0.82640117 0.93129486 0.70957192]


In [ ]:
a=rd.randint(4)#0,1,2,3,4
print(a)

2


In [ ]:
a=rd.randint(4,size=6)#limit
print(a)

[3 2 3 2 1 1]


In [ ]:
a=rd.randint(50,size=(2,3))#limit
print(a)

[[ 7 47 12]
 [12 25 17]]


In [ ]:
#joins
a=np.array([1,2,3])
b=np.array([4,5,6])
#1x4+2x5+3x6
print(np.inner(a,b))

32


In [ ]:
#joins
a=np.array([1,2,3])
b=np.array([4,5,6])
#1(4,5,6)2(4,5,6)3(4,5,6)
print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#cross joint
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.cross(a,b))

[-3  6 -3]
